# Generated by Django 5.2 on 2026-04-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auth_user_and_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="core.user",
            ),
        ),
    ]
