# Generated by Django 5.2 on 2026-04-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_activesession_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"ordering": ["position", "added_at"]},
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.watchlist",
            ),
        ),
    ]
