# Generated by Django 5.2 on 2026-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auth_user_and_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("close", models.FloatField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "price_cache",
                "indexes": [
                    models.Index(
                        fields=["symbol", "date"], name="price_cache_symbol_a16ec2_idx"
                    )
                ],
                "unique_together": {("symbol", "date")},
            },
        ),
    ]
