# Generated by Django 5.2 on 2026-05-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_watchlistitem_options_watchlistitem_position_and_more'),
        ('core', '0005_pricecache'),
    ]

    operations = [
    ]
